language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - hhvm

before_install:
  - composer self-update
  - composer config preferred-install source

install: composer install --no-interaction --no-progress

script:
  - vendor/bin/phpcs --standard=PSR2 -n src tests
  - vendor/bin/phpunit
  - php example/CreateTransfer.php

after_success:
  - php vendor/bin/php-coveralls -v
